version: '3.7'

services:
  web:
    build: .
    image: blogapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/blog
    expose:
      - "8000"
    # This will run 4 instances of the web. Eventually 4 docker containers will be created.
    scale: 4
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    build: ./nginx
    volumes:
      - ./static/:/home/app/blog/static/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
